CREATE TABLE CONSULTAS (
                           ID BIGSERIAL PRIMARY KEY,
                           MEDICO_ID BIGINT NOT NULL,
                           PACIENTE_ID BIGINT NOT NULL,
                           DATA TIMESTAMP NOT NULL,

                           CONSTRAINT FK_CONSULTAS_MEDICO_ID FOREIGN KEY(MEDICO_ID) REFERENCES MEDICOS(ID),
                           CONSTRAINT FK_CONSULTAS_PACIENTE_ID FOREIGN KEY(PACIENTE_ID) REFERENCES PACIENTES(ID)
);